local ____lualib = require("lualib_bundle")
local __TS__SourceMapTraceBack = ____lualib.__TS__SourceMapTraceBack
__TS__SourceMapTraceBack(debug.getinfo(1).short_src, {["5"] = 9,["8"] = 15,["9"] = 17,["10"] = 17,["11"] = 18,["12"] = 18,["13"] = 19,["14"] = 19,["15"] = 21,["16"] = 21,["17"] = 22,["18"] = 22,["19"] = 23,["20"] = 23,["21"] = 24,["22"] = 24,["23"] = 25,["24"] = 25,["25"] = 27,["26"] = 27,["27"] = 28,["28"] = 28,["29"] = 29,["30"] = 29,["31"] = 30,["32"] = 30,["33"] = 31,["34"] = 31,["35"] = 32,["36"] = 32,["37"] = 33,["38"] = 33,["39"] = 34,["40"] = 34,["41"] = 36,["42"] = 36,["43"] = 37,["44"] = 37,["45"] = 38,["46"] = 38,["47"] = 39,["48"] = 39,["49"] = 40,["50"] = 40,["51"] = 41,["52"] = 41,["53"] = 42,["54"] = 42,["55"] = 43,["56"] = 43,["57"] = 44,["58"] = 44,["59"] = 45,["60"] = 45,["61"] = 46,["62"] = 46,["63"] = 47,["64"] = 47,["65"] = 48,["66"] = 48,["67"] = 49,["68"] = 49,["69"] = 50,["70"] = 50});
local ____exports = {}
____exports.protobufPackage = "protocol"
--- 消息ID映射表
-- 用于消息路由和识别
____exports.MessageId = ____exports.MessageId or ({})
____exports.MessageId.UNKNOWN = 0
____exports.MessageId[____exports.MessageId.UNKNOWN] = "UNKNOWN"
____exports.MessageId.PING = 1
____exports.MessageId[____exports.MessageId.PING] = "PING"
____exports.MessageId.PONG = 2
____exports.MessageId[____exports.MessageId.PONG] = "PONG"
____exports.MessageId.GATEWAY_HEARTBEAT_REQ = 100
____exports.MessageId[____exports.MessageId.GATEWAY_HEARTBEAT_REQ] = "GATEWAY_HEARTBEAT_REQ"
____exports.MessageId.GATEWAY_HEARTBEAT_RSP = 101
____exports.MessageId[____exports.MessageId.GATEWAY_HEARTBEAT_RSP] = "GATEWAY_HEARTBEAT_RSP"
____exports.MessageId.GATEWAY_CONNECT_REQ = 102
____exports.MessageId[____exports.MessageId.GATEWAY_CONNECT_REQ] = "GATEWAY_CONNECT_REQ"
____exports.MessageId.GATEWAY_CONNECT_RSP = 103
____exports.MessageId[____exports.MessageId.GATEWAY_CONNECT_RSP] = "GATEWAY_CONNECT_RSP"
____exports.MessageId.GATEWAY_DISCONNECT_NOTIFY = 104
____exports.MessageId[____exports.MessageId.GATEWAY_DISCONNECT_NOTIFY] = "GATEWAY_DISCONNECT_NOTIFY"
____exports.MessageId.LOGIN_LOGIN_REQ = 200
____exports.MessageId[____exports.MessageId.LOGIN_LOGIN_REQ] = "LOGIN_LOGIN_REQ"
____exports.MessageId.LOGIN_LOGIN_RSP = 201
____exports.MessageId[____exports.MessageId.LOGIN_LOGIN_RSP] = "LOGIN_LOGIN_RSP"
____exports.MessageId.LOGIN_LOGOUT_REQ = 202
____exports.MessageId[____exports.MessageId.LOGIN_LOGOUT_REQ] = "LOGIN_LOGOUT_REQ"
____exports.MessageId.LOGIN_LOGOUT_RSP = 203
____exports.MessageId[____exports.MessageId.LOGIN_LOGOUT_RSP] = "LOGIN_LOGOUT_RSP"
____exports.MessageId.LOGIN_VALIDATE_TOKEN_REQ = 204
____exports.MessageId[____exports.MessageId.LOGIN_VALIDATE_TOKEN_REQ] = "LOGIN_VALIDATE_TOKEN_REQ"
____exports.MessageId.LOGIN_VALIDATE_TOKEN_RSP = 205
____exports.MessageId[____exports.MessageId.LOGIN_VALIDATE_TOKEN_RSP] = "LOGIN_VALIDATE_TOKEN_RSP"
____exports.MessageId.LOGIN_GET_ONLINE_COUNT_REQ = 206
____exports.MessageId[____exports.MessageId.LOGIN_GET_ONLINE_COUNT_REQ] = "LOGIN_GET_ONLINE_COUNT_REQ"
____exports.MessageId.LOGIN_GET_ONLINE_COUNT_RSP = 207
____exports.MessageId[____exports.MessageId.LOGIN_GET_ONLINE_COUNT_RSP] = "LOGIN_GET_ONLINE_COUNT_RSP"
____exports.MessageId.GAME_ENTER_REQ = 300
____exports.MessageId[____exports.MessageId.GAME_ENTER_REQ] = "GAME_ENTER_REQ"
____exports.MessageId.GAME_ENTER_RSP = 301
____exports.MessageId[____exports.MessageId.GAME_ENTER_RSP] = "GAME_ENTER_RSP"
____exports.MessageId.GAME_LEAVE_REQ = 302
____exports.MessageId[____exports.MessageId.GAME_LEAVE_REQ] = "GAME_LEAVE_REQ"
____exports.MessageId.GAME_LEAVE_RSP = 303
____exports.MessageId[____exports.MessageId.GAME_LEAVE_RSP] = "GAME_LEAVE_RSP"
____exports.MessageId.GAME_GET_PLAYER_INFO_REQ = 304
____exports.MessageId[____exports.MessageId.GAME_GET_PLAYER_INFO_REQ] = "GAME_GET_PLAYER_INFO_REQ"
____exports.MessageId.GAME_GET_PLAYER_INFO_RSP = 305
____exports.MessageId[____exports.MessageId.GAME_GET_PLAYER_INFO_RSP] = "GAME_GET_PLAYER_INFO_RSP"
____exports.MessageId.GAME_UPDATE_PLAYER_REQ = 306
____exports.MessageId[____exports.MessageId.GAME_UPDATE_PLAYER_REQ] = "GAME_UPDATE_PLAYER_REQ"
____exports.MessageId.GAME_UPDATE_PLAYER_RSP = 307
____exports.MessageId[____exports.MessageId.GAME_UPDATE_PLAYER_RSP] = "GAME_UPDATE_PLAYER_RSP"
____exports.MessageId.GAME_GET_ONLINE_PLAYERS_REQ = 308
____exports.MessageId[____exports.MessageId.GAME_GET_ONLINE_PLAYERS_REQ] = "GAME_GET_ONLINE_PLAYERS_REQ"
____exports.MessageId.GAME_GET_ONLINE_PLAYERS_RSP = 309
____exports.MessageId[____exports.MessageId.GAME_GET_ONLINE_PLAYERS_RSP] = "GAME_GET_ONLINE_PLAYERS_RSP"
____exports.MessageId.GAME_ADD_EXP_REQ = 310
____exports.MessageId[____exports.MessageId.GAME_ADD_EXP_REQ] = "GAME_ADD_EXP_REQ"
____exports.MessageId.GAME_ADD_EXP_RSP = 311
____exports.MessageId[____exports.MessageId.GAME_ADD_EXP_RSP] = "GAME_ADD_EXP_RSP"
____exports.MessageId.GAME_ADD_GOLD_REQ = 312
____exports.MessageId[____exports.MessageId.GAME_ADD_GOLD_REQ] = "GAME_ADD_GOLD_REQ"
____exports.MessageId.GAME_ADD_GOLD_RSP = 313
____exports.MessageId[____exports.MessageId.GAME_ADD_GOLD_RSP] = "GAME_ADD_GOLD_RSP"
____exports.MessageId.UNRECOGNIZED = -1
____exports.MessageId[____exports.MessageId.UNRECOGNIZED] = "UNRECOGNIZED"
return ____exports
