// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v4.24.4
// source: common.proto

/* eslint-disable */

export const protobufPackage = "common";

/** 错误码定义 */
export enum ErrorCode {
  /** SUCCESS - 成功 */
  SUCCESS = 0,
  /** UNKNOWN_ERROR - 未知错误 */
  UNKNOWN_ERROR = 1,
  /** INVALID_REQUEST - 无效请求 */
  INVALID_REQUEST = 2,
  /** UNAUTHORIZED - 未授权 */
  UNAUTHORIZED = 3,
  /** FORBIDDEN - 禁止访问 */
  FORBIDDEN = 4,
  /** NOT_FOUND - 未找到 */
  NOT_FOUND = 5,
  /** TIMEOUT - 超时 */
  TIMEOUT = 6,
  /** INTERNAL_ERROR - 内部错误 */
  INTERNAL_ERROR = 7,
  /** SERVICE_UNAVAILABLE - 服务不可用 */
  SERVICE_UNAVAILABLE = 8,
  UNRECOGNIZED = -1,
}

/**
 * 通用消息包装
 * 所有消息都通过这个结构发送
 */
export interface Packet {
  /** 消息ID */
  msgId: number;
  /** 会话ID（用于请求响应匹配） */
  session: number;
  /** 消息体（具体消息的序列化数据） */
  data: Uint8Array;
  /** 时间戳 */
  timestamp: number;
}

/** 通用响应 */
export interface Response {
  /** 错误码 */
  code: ErrorCode;
  /** 错误信息 */
  message: string;
  /** 响应数据 */
  data: Uint8Array;
}
