// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v4.24.4
// source: game.proto

/* eslint-disable */
import type { ErrorCode } from "./common";

export const protobufPackage = "game";

/** 玩家信息 */
export interface PlayerInfo {
  /** 用户ID */
  userId: number;
  /** 等级 */
  level: number;
  /** 经验值 */
  exp: number;
  /** 金币 */
  gold: number;
  /** 进入时间 */
  enterTime: number;
}

/** 进入游戏请求 */
export interface EnterGameRequest {
  userId: number;
  /** 登录token */
  token: string;
}

/** 进入游戏响应 */
export interface EnterGameResponse {
  code: ErrorCode;
  message: string;
  /** 玩家信息 */
  player?: PlayerInfo | undefined;
}

/** 离开游戏请求 */
export interface LeaveGameRequest {
  userId: number;
}

/** 离开游戏响应 */
export interface LeaveGameResponse {
  code: ErrorCode;
  message: string;
}

/** 获取玩家信息请求 */
export interface GetPlayerInfoRequest {
  userId: number;
}

/** 获取玩家信息响应 */
export interface GetPlayerInfoResponse {
  code: ErrorCode;
  message: string;
  player?: PlayerInfo | undefined;
}

/** 玩家属性更新 */
export interface PlayerUpdate {
  /** 等级（0表示不更新） */
  level: number;
  /** 经验值（0表示不更新） */
  exp: number;
  /** 金币（0表示不更新） */
  gold: number;
}

/** 更新玩家信息请求 */
export interface UpdatePlayerRequest {
  userId: number;
  update?: PlayerUpdate | undefined;
}

/** 更新玩家信息响应 */
export interface UpdatePlayerResponse {
  code: ErrorCode;
  message: string;
  /** 更新后的玩家信息 */
  player?: PlayerInfo | undefined;
}

/** 获取在线玩家数请求 */
export interface GetOnlinePlayersRequest {
}

/** 获取在线玩家数响应 */
export interface GetOnlinePlayersResponse {
  count: number;
  /** 在线玩家列表 */
  players: PlayerInfo[];
}

/** 增加经验请求 */
export interface AddExpRequest {
  userId: number;
  /** 经验值数量 */
  expAmount: number;
}

/** 增加经验响应 */
export interface AddExpResponse {
  code: ErrorCode;
  message: string;
  /** 更新后的玩家信息 */
  player?:
    | PlayerInfo
    | undefined;
  /** 是否升级 */
  levelUp: boolean;
}

/** 增加金币请求 */
export interface AddGoldRequest {
  userId: number;
  /** 金币数量 */
  goldAmount: number;
}

/** 增加金币响应 */
export interface AddGoldResponse {
  code: ErrorCode;
  message: string;
  /** 更新后的玩家信息 */
  player?: PlayerInfo | undefined;
}
