// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v4.24.4
// source: gateway.proto

/* eslint-disable */
import type { ErrorCode } from "./common";

export const protobufPackage = "gateway";

/** 消息类型枚举 */
export enum MessageType {
  /** HEARTBEAT - 心跳 */
  HEARTBEAT = 0,
  /** CONNECT - 连接 */
  CONNECT = 1,
  /** DISCONNECT - 断开 */
  DISCONNECT = 2,
  /** FORWARD - 转发 */
  FORWARD = 3,
  /** BROADCAST - 广播 */
  BROADCAST = 4,
  /** KICK - 踢出 */
  KICK = 5,
  UNRECOGNIZED = -1,
}

/** 心跳请求 */
export interface HeartbeatRequest {
  /** 客户端时间戳 */
  clientTime: number;
}

/** 心跳响应 */
export interface HeartbeatResponse {
  /** 服务器时间戳 */
  serverTime: number;
  /** 在线人数 */
  onlineCount: number;
}

/** 客户端信息 */
export interface ClientInfo {
  /** IP地址 */
  ip: string;
  /** 端口 */
  port: number;
  /** 客户端版本 */
  version: string;
  /** 平台（iOS/Android/Web） */
  platform: string;
  /** 设备ID */
  deviceId: string;
}

/** 连接请求 */
export interface ConnectRequest {
  clientInfo?:
    | ClientInfo
    | undefined;
  /** 登录token（可选） */
  token: string;
}

/** 连接响应 */
export interface ConnectResponse {
  code: ErrorCode;
  message: string;
  /** 连接ID */
  connId: number;
  /** 服务器时间 */
  serverTime: number;
}

/** 断开连接通知 */
export interface DisconnectNotify {
  connId: number;
  /** 断开原因 */
  reason: string;
}
