// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v4.24.4
// source: login.proto

/* eslint-disable */
import type { ErrorCode } from "./common";

export const protobufPackage = "login";

/** 登录请求 */
export interface LoginRequest {
  /** 用户名 */
  username: string;
  /** 密码（应该是加密后的） */
  password: string;
  /** 设备ID */
  deviceId: string;
  /** 平台 */
  platform: string;
}

/** 登录响应 */
export interface LoginResponse {
  code: ErrorCode;
  message: string;
  /** 用户信息 */
  user?:
    | UserInfo
    | undefined;
  /** 登录token */
  token: string;
}

/** 用户信息 */
export interface UserInfo {
  /** 用户ID */
  userId: number;
  /** 用户名 */
  username: string;
  /** 登录时间 */
  loginTime: number;
  /** 等级 */
  level: number;
  /** 经验值 */
  exp: number;
}

/** 登出请求 */
export interface LogoutRequest {
  userId: number;
}

/** 登出响应 */
export interface LogoutResponse {
  code: ErrorCode;
  message: string;
}

/** Token验证请求 */
export interface ValidateTokenRequest {
  token: string;
}

/** Token验证响应 */
export interface ValidateTokenResponse {
  code: ErrorCode;
  message: string;
  userId: number;
  /** 是否有效 */
  valid: boolean;
}

/** 获取在线用户数请求 */
export interface GetOnlineCountRequest {
}

/** 获取在线用户数响应 */
export interface GetOnlineCountResponse {
  count: number;
}
